[extern]
function_hints = [
  { from = "examples::camtest::freenect_init", to = "src::core::freenect_init" },
  { from = "examples::camtest::freenect_shutdown", to = "src::core::freenect_shutdown" },
  { from = "examples::camtest::freenect_set_log_level", to = "src::core::freenect_set_log_level" },
  { from = "examples::camtest::freenect_process_events", to = "src::core::freenect_process_events" },
  { from = "examples::camtest::freenect_num_devices", to = "src::core::freenect_num_devices" },
  { from = "examples::camtest::freenect_select_subdevices", to = "src::core::freenect_select_subdevices" },
  { from = "examples::camtest::freenect_open_device", to = "src::core::freenect_open_device" },
  { from = "examples::camtest::freenect_close_device", to = "src::core::freenect_close_device" },
  { from = "examples::camtest::freenect_set_depth_callback", to = "src::cameras::freenect_set_depth_callback" },
  { from = "examples::camtest::freenect_set_video_callback", to = "src::cameras::freenect_set_video_callback" },
  { from = "examples::camtest::freenect_start_depth", to = "src::cameras::freenect_start_depth" },
  { from = "examples::camtest::freenect_start_video", to = "src::cameras::freenect_start_video" },
  { from = "examples::camtest::freenect_stop_depth", to = "src::cameras::freenect_stop_depth" },
  { from = "examples::camtest::freenect_stop_video", to = "src::cameras::freenect_stop_video" },
  { from = "examples::camtest::freenect_find_video_mode", to = "src::cameras::freenect_find_video_mode" },
  { from = "examples::camtest::freenect_set_video_mode", to = "src::cameras::freenect_set_video_mode" },
  { from = "examples::camtest::freenect_find_depth_mode", to = "src::cameras::freenect_find_depth_mode" },
  { from = "examples::camtest::freenect_set_depth_mode", to = "src::cameras::freenect_set_depth_mode" },
  { from = "examples::chunkview::freenect_init", to = "src::core::freenect_init" },
  { from = "examples::chunkview::freenect_shutdown", to = "src::core::freenect_shutdown" },
  { from = "examples::chunkview::freenect_set_log_level", to = "src::core::freenect_set_log_level" },
  { from = "examples::chunkview::freenect_process_events", to = "src::core::freenect_process_events" },
  { from = "examples::chunkview::freenect_num_devices", to = "src::core::freenect_num_devices" },
  { from = "examples::chunkview::freenect_select_subdevices", to = "src::core::freenect_select_subdevices" },
  { from = "examples::chunkview::freenect_open_device", to = "src::core::freenect_open_device" },
  { from = "examples::chunkview::freenect_close_device", to = "src::core::freenect_close_device" },
  { from = "examples::chunkview::freenect_set_depth_callback", to = "src::cameras::freenect_set_depth_callback" },
  { from = "examples::chunkview::freenect_start_depth", to = "src::cameras::freenect_start_depth" },
  { from = "examples::chunkview::freenect_stop_depth", to = "src::cameras::freenect_stop_depth" },
  { from = "examples::chunkview::freenect_update_tilt_state", to = "src::tilt::freenect_update_tilt_state" },
  { from = "examples::chunkview::freenect_get_tilt_state", to = "src::tilt::freenect_get_tilt_state" },
  { from = "examples::chunkview::freenect_set_tilt_degs", to = "src::tilt::freenect_set_tilt_degs" },
  { from = "examples::chunkview::freenect_set_led", to = "src::tilt::freenect_set_led" },
  { from = "examples::chunkview::freenect_get_mks_accel", to = "src::tilt::freenect_get_mks_accel" },
  { from = "examples::chunkview::freenect_find_depth_mode", to = "src::cameras::freenect_find_depth_mode" },
  { from = "examples::chunkview::freenect_set_depth_mode", to = "src::cameras::freenect_set_depth_mode" },
  { from = "examples::glview::freenect_init", to = "src::core::freenect_init" },
  { from = "examples::glview::freenect_shutdown", to = "src::core::freenect_shutdown" },
  { from = "examples::glview::freenect_set_log_level", to = "src::core::freenect_set_log_level" },
  { from = "examples::glview::freenect_process_events", to = "src::core::freenect_process_events" },
  { from = "examples::glview::freenect_num_devices", to = "src::core::freenect_num_devices" },
  { from = "examples::glview::freenect_select_subdevices", to = "src::core::freenect_select_subdevices" },
  { from = "examples::glview::freenect_open_device", to = "src::core::freenect_open_device" },
  { from = "examples::glview::freenect_close_device", to = "src::core::freenect_close_device" },
  { from = "examples::glview::freenect_set_depth_callback", to = "src::cameras::freenect_set_depth_callback" },
  { from = "examples::glview::freenect_set_video_callback", to = "src::cameras::freenect_set_video_callback" },
  { from = "examples::glview::freenect_set_video_buffer", to = "src::cameras::freenect_set_video_buffer" },
  { from = "examples::glview::freenect_start_depth", to = "src::cameras::freenect_start_depth" },
  { from = "examples::glview::freenect_start_video", to = "src::cameras::freenect_start_video" },
  { from = "examples::glview::freenect_stop_depth", to = "src::cameras::freenect_stop_depth" },
  { from = "examples::glview::freenect_set_ir_brightness", to = "src::flags::freenect_set_ir_brightness" },
  { from = "examples::glview::freenect_get_ir_brightness", to = "src::flags::freenect_get_ir_brightness" },
  { from = "examples::glview::freenect_set_depth_mode", to = "src::cameras::freenect_set_depth_mode" },
  { from = "examples::glview::freenect_find_depth_mode", to = "src::cameras::freenect_find_depth_mode" },
  { from = "examples::glview::freenect_find_video_mode", to = "src::cameras::freenect_find_video_mode" },
  { from = "examples::glview::freenect_stop_video", to = "src::cameras::freenect_stop_video" },
  { from = "examples::glview::freenect_update_tilt_state", to = "src::tilt::freenect_update_tilt_state" },
  { from = "examples::glview::freenect_get_tilt_state", to = "src::tilt::freenect_get_tilt_state" },
  { from = "examples::glview::freenect_set_tilt_degs", to = "src::tilt::freenect_set_tilt_degs" },
  { from = "examples::glview::freenect_set_led", to = "src::tilt::freenect_set_led" },
  { from = "examples::glview::freenect_get_mks_accel", to = "src::tilt::freenect_get_mks_accel" },
  { from = "examples::glview::freenect_set_video_mode", to = "src::cameras::freenect_set_video_mode" },
  { from = "examples::hiview::freenect_init", to = "src::core::freenect_init" },
  { from = "examples::hiview::freenect_shutdown", to = "src::core::freenect_shutdown" },
  { from = "examples::hiview::freenect_set_log_level", to = "src::core::freenect_set_log_level" },
  { from = "examples::hiview::freenect_process_events", to = "src::core::freenect_process_events" },
  { from = "examples::hiview::freenect_num_devices", to = "src::core::freenect_num_devices" },
  { from = "examples::hiview::freenect_select_subdevices", to = "src::core::freenect_select_subdevices" },
  { from = "examples::hiview::freenect_open_device", to = "src::core::freenect_open_device" },
  { from = "examples::hiview::freenect_close_device", to = "src::core::freenect_close_device" },
  { from = "examples::hiview::freenect_set_depth_callback", to = "src::cameras::freenect_set_depth_callback" },
  { from = "examples::hiview::freenect_set_video_callback", to = "src::cameras::freenect_set_video_callback" },
  { from = "examples::hiview::freenect_set_video_buffer", to = "src::cameras::freenect_set_video_buffer" },
  { from = "examples::hiview::freenect_start_depth", to = "src::cameras::freenect_start_depth" },
  { from = "examples::hiview::freenect_start_video", to = "src::cameras::freenect_start_video" },
  { from = "examples::hiview::freenect_stop_depth", to = "src::cameras::freenect_stop_depth" },
  { from = "examples::hiview::freenect_set_depth_mode", to = "src::cameras::freenect_set_depth_mode" },
  { from = "examples::hiview::freenect_find_depth_mode", to = "src::cameras::freenect_find_depth_mode" },
  { from = "examples::hiview::freenect_find_video_mode", to = "src::cameras::freenect_find_video_mode" },
  { from = "examples::hiview::freenect_stop_video", to = "src::cameras::freenect_stop_video" },
  { from = "examples::hiview::freenect_set_led", to = "src::tilt::freenect_set_led" },
  { from = "examples::hiview::freenect_get_current_video_mode", to = "src::cameras::freenect_get_current_video_mode" },
  { from = "examples::hiview::freenect_set_video_mode", to = "src::cameras::freenect_set_video_mode" },
  { from = "examples::micview::freenect_init", to = "src::core::freenect_init" },
  { from = "examples::micview::freenect_shutdown", to = "src::core::freenect_shutdown" },
  { from = "examples::micview::freenect_set_log_level", to = "src::core::freenect_set_log_level" },
  { from = "examples::micview::freenect_process_events", to = "src::core::freenect_process_events" },
  { from = "examples::micview::freenect_num_devices", to = "src::core::freenect_num_devices" },
  { from = "examples::micview::freenect_select_subdevices", to = "src::core::freenect_select_subdevices" },
  { from = "examples::micview::freenect_open_device", to = "src::core::freenect_open_device" },
  { from = "examples::micview::freenect_close_device", to = "src::core::freenect_close_device" },
  { from = "examples::micview::freenect_set_user", to = "src::core::freenect_set_user" },
  { from = "examples::micview::freenect_get_user", to = "src::core::freenect_get_user" },
  { from = "examples::regview::freenect_init", to = "src::core::freenect_init" },
  { from = "examples::regview::freenect_process_events", to = "src::core::freenect_process_events" },
  { from = "examples::regview::freenect_num_devices", to = "src::core::freenect_num_devices" },
  { from = "examples::regview::freenect_select_subdevices", to = "src::core::freenect_select_subdevices" },
  { from = "examples::regview::freenect_open_device", to = "src::core::freenect_open_device" },
  { from = "examples::regview::freenect_close_device", to = "src::core::freenect_close_device" },
  { from = "examples::regview::freenect_set_depth_callback", to = "src::cameras::freenect_set_depth_callback" },
  { from = "examples::regview::freenect_set_video_callback", to = "src::cameras::freenect_set_video_callback" },
  { from = "examples::regview::freenect_set_video_buffer", to = "src::cameras::freenect_set_video_buffer" },
  { from = "examples::regview::freenect_start_depth", to = "src::cameras::freenect_start_depth" },
  { from = "examples::regview::freenect_start_video", to = "src::cameras::freenect_start_video" },
  { from = "examples::regview::freenect_stop_depth", to = "src::cameras::freenect_stop_depth" },
  { from = "examples::regview::freenect_stop_video", to = "src::cameras::freenect_stop_video" },
  { from = "examples::regview::freenect_set_log_level", to = "src::core::freenect_set_log_level" },
  { from = "examples::regview::freenect_shutdown", to = "src::core::freenect_shutdown" },
  { from = "examples::regview::freenect_find_depth_mode", to = "src::cameras::freenect_find_depth_mode" },
  { from = "examples::regview::freenect_find_video_mode", to = "src::cameras::freenect_find_video_mode" },
  { from = "examples::regview::freenect_set_video_mode", to = "src::cameras::freenect_set_video_mode" },
  { from = "examples::regview::freenect_set_depth_mode", to = "src::cameras::freenect_set_depth_mode" },
  { from = "examples::tiltdemo::freenect_get_mks_accel", to = "src::tilt::freenect_get_mks_accel" },
  { from = "examples::wavrecord::freenect_init", to = "src::core::freenect_init" },
  { from = "examples::wavrecord::freenect_shutdown", to = "src::core::freenect_shutdown" },
  { from = "examples::wavrecord::freenect_set_log_level", to = "src::core::freenect_set_log_level" },
  { from = "examples::wavrecord::freenect_process_events", to = "src::core::freenect_process_events" },
  { from = "examples::wavrecord::freenect_num_devices", to = "src::core::freenect_num_devices" },
  { from = "examples::wavrecord::freenect_select_subdevices", to = "src::core::freenect_select_subdevices" },
  { from = "examples::wavrecord::freenect_open_device", to = "src::core::freenect_open_device" },
  { from = "examples::wavrecord::freenect_set_user", to = "src::core::freenect_set_user" },
  { from = "examples::wavrecord::freenect_get_user", to = "src::core::freenect_get_user" },
  { from = "wrappers::c_sync::libfreenect_sync::freenect_init", to = "src::core::freenect_init" },
  { from = "wrappers::c_sync::libfreenect_sync::freenect_shutdown", to = "src::core::freenect_shutdown" },
  { from = "wrappers::c_sync::libfreenect_sync::freenect_process_events", to = "src::core::freenect_process_events" },
  { from = "wrappers::c_sync::libfreenect_sync::freenect_select_subdevices", to = "src::core::freenect_select_subdevices" },
  { from = "wrappers::c_sync::libfreenect_sync::freenect_open_device", to = "src::core::freenect_open_device" },
  { from = "wrappers::c_sync::libfreenect_sync::freenect_close_device", to = "src::core::freenect_close_device" },
  { from = "wrappers::c_sync::libfreenect_sync::freenect_set_user", to = "src::core::freenect_set_user" },
  { from = "wrappers::c_sync::libfreenect_sync::freenect_get_user", to = "src::core::freenect_get_user" },
  { from = "wrappers::c_sync::libfreenect_sync::freenect_set_depth_callback", to = "src::cameras::freenect_set_depth_callback" },
  { from = "wrappers::c_sync::libfreenect_sync::freenect_set_video_callback", to = "src::cameras::freenect_set_video_callback" },
  { from = "wrappers::c_sync::libfreenect_sync::freenect_set_depth_buffer", to = "src::cameras::freenect_set_depth_buffer" },
  { from = "wrappers::c_sync::libfreenect_sync::freenect_set_video_buffer", to = "src::cameras::freenect_set_video_buffer" },
  { from = "wrappers::c_sync::libfreenect_sync::freenect_start_depth", to = "src::cameras::freenect_start_depth" },
  { from = "wrappers::c_sync::libfreenect_sync::freenect_start_video", to = "src::cameras::freenect_start_video" },
  { from = "wrappers::c_sync::libfreenect_sync::freenect_stop_depth", to = "src::cameras::freenect_stop_depth" },
  { from = "wrappers::c_sync::libfreenect_sync::freenect_stop_video", to = "src::cameras::freenect_stop_video" },
  { from = "wrappers::c_sync::libfreenect_sync::freenect_update_tilt_state", to = "src::tilt::freenect_update_tilt_state" },
  { from = "wrappers::c_sync::libfreenect_sync::freenect_get_tilt_state", to = "src::tilt::freenect_get_tilt_state" },
  { from = "wrappers::c_sync::libfreenect_sync::freenect_set_tilt_degs", to = "src::tilt::freenect_set_tilt_degs" },
  { from = "wrappers::c_sync::libfreenect_sync::freenect_set_led", to = "src::tilt::freenect_set_led" },
  { from = "wrappers::c_sync::libfreenect_sync::freenect_find_video_mode", to = "src::cameras::freenect_find_video_mode" },
  { from = "wrappers::c_sync::libfreenect_sync::freenect_set_video_mode", to = "src::cameras::freenect_set_video_mode" },
  { from = "wrappers::c_sync::libfreenect_sync::freenect_find_depth_mode", to = "src::cameras::freenect_find_depth_mode" },
  { from = "wrappers::c_sync::libfreenect_sync::freenect_set_depth_mode", to = "src::cameras::freenect_set_depth_mode" },
]
