[package]
name = "passes"
version = "0.1.0"
edition = "2024"

[dependencies]
utils = { path = "../utils" }
serde.workspace = true
serde_json.workspace = true
etrace.workspace = true
typed-arena.workspace = true
toml_edit.workspace = true

[package.metadata.rust-analyzer]
rustc_private = true
